# Shopify App configuration
client_id = "15673a82b49113d07a0f066fd048267e"
name = "ShopiBundle"
application_url = "https://shopi-bundle.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "write_metaobjects,read_metaobjects,write_metaobject_definitions,read_products,write_discounts,read_orders" 

[auth]
redirect_urls = [
    "https://shopi-bundle.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://shopi-bundle.vercel.app/api/proxy_route"
subpath = "proxy"
prefix = "apps"
